# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  database: highcharts
  username: root
  password:
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and
production:
  adapter: mysql
  database: highcharts_production
  username: root
  password:
